### ISSUE TITLE
Playing a track clears playlist

### ISSUE THREAD

**Issue by perguth** [peermusic/desktop#2]
1. Add a few tracks to the queue
2. Click on a track in the inventory (so that it gets immediately played)

_=> Queue gets cleared_

**Expected:** Start playing immediately but do not clear the playlist. This behavior was not written down but I think that is what we envisioned in our discussion, right?!

---

peermusic/user-stories/issues/15

**Comment by queicherius** [comment]
> Expected: Start playing immediately but do not clear the playlist. This behavior was not written down but I think that is what we envisioned in our discussion, right?!

We actually said in our discussion that this is exactly the behavior we want. If you click on a track in an album you expect the album to be played, not the single track and then the rest of your queued entries. More discussion needed?

**Comment by queicherius** [comment]
In the new implementation of the queue functionality (16fe6cff1060b26046f48e09844021294d48485c) this is fixed.
