### ISSUE TITLE
Issue with install on OSX 

### ISSUE THREAD

**Issue by freedomtrain** [peermusic/desktop#53]
The app seems to be Amazing !!!
I'am having issue installing on OSX
When I npm install -g gulp
I receive the following 

npm install -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN checkPermissions Missing write access to /Users/hwrapbrown/.npm-packages/lib/node_modules/gulp
/Users/hwrapbrown/.npm-packages/lib
└── gulp@3.9.1 

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node5/5.12.0/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path /Users/hwrapbrown/.npm-packages/lib/node_modules/gulp
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/hwrapbrown/.npm-packages/lib/node_modules/gulp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/hwrapbrown/.npm-packages/lib/node_modules/gulp']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/hwrapbrown/.npm-packages/lib/node_modules/gulp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

**Comment by queicherius** [comment]
The issue is that your `npm` command does not have the rights to write in your home directory. You can fix that using any of the following methods:
1. Follow [this guide](https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/) to setup global npm scripts without administrator
2. Run the command with `sudo` in front like this: `sudo npm install -g gulp`. This effectively gives the command administrator rights, which allows it to write the file.
3. Install (and run) the local version by using `npm install gulp` (note the missing `-g` flag) and instead of the last step (`gulp`) running `./node_modules/.bin/gulp`

**Comment by freedomtrain** [comment]
Thanks !!!! I will test out the options

**Comment by freedomtrain** [comment]
Thanks so much !!!!
I was able to start the app !!!

Do we need to run a singal hub server in order to invite users ?
Is it possible to peer music users to also be hub servers ?

 

On September 6, 2016 at 4:41:31 PM, David Reeß (notifications@github.com) wrote:

The issue is that your npm command does not have the rights to write in your home directory. You can fix that using any of the following methods:

Follow this guide to setup global npm scripts without administrator
Run the command with sudo in front like this: sudo npm install -g gulp. This effectively gives the command administrator rights, which allows it to write the file.
Install (and run) the local version by using npm install gulp (note the missing -g flag) and instead of the last step (gulp) running ./node_modules/.bin/gulp

**Comment by queicherius** [comment]
> Thanks so much !!!!
> I was able to start the app !!!

Nice! Glad to hear you got it working. :+1: 

> Do we need to run a singal hub server in order to invite users ?
> Is it possible to peer music users to also be hub servers ?

@pguth can probably explain that better, but the gist is yes, you need a signalhub server and yes you can run a hub server on the same machine as the interface (just on a different port)

**Comment by freedomtrain** [comment]
We are looking to have some of our coop begin using peermusic
At http://localhost:8000/#/manage-friends/issue what should be entered into the Hub URL field ?

**Comment by queicherius** [comment]
The hub url has to be a running signal hub server. :)

**Comment by perguth** [comment]
You could use eg. https://signalhub.perguth.de:65300/

**Comment by freedomtrain** [comment]
got it !!!
our coop members are not very technical. 
is there a way to hardcode the signal hub address so the members url filed would be filled in with a running signalhub url ?

Thanks so much for your help !!!!

On September 26, 2016 at 12:09:12 PM, Per Guth (notifications@github.com) wrote:

You could use eg. https://signalhub.perguth.de:65300/

**Comment by freedomtrain** [comment]
can a user have local signalhub server on http://localhost:7000 as there signalhub server ?
Would it be possible for the users to send invites with a signalhub server on http://localhost:700

Thanks

**Comment by perguth** [comment]
Nope. The server needs to be reachable for all participants that want to reach each other.

**Comment by freedomtrain** [comment]
Great !!!
I understand !!!
Can I hard code the server url so that non technical users will not have to enter the url ?

On September 26, 2016 at 12:22:07 PM, Per Guth (notifications@github.com) wrote:

Nope. The server needs to be reachable for all participants that want to reach each other.

**Comment by perguth** [comment]
> Can I hard code the server url so that non technical users will not have to enter the url ?

We will do that for you and update https://peermusic.github.io/#/songs/all

**Comment by freedomtrain** [comment]
Thanks !!!!

On September 26, 2016 at 12:24:20 PM, Per Guth (notifications@github.com) wrote:

Can I hard code the server url so that non technical users will not have to enter the url ?

We will do that for you and update https://peermusic.github.io/#/songs/all

**Comment by freedomtrain** [comment]
I have set up a signalhub here https://signalhubmonk.herokuapp.com/

**Comment by perguth** [comment]
Cool :D
