### ISSUE TITLE
how can we turn off http://localhost:7000  

### ISSUE THREAD

**Issue by freedomtrain** [peermusic/desktop#56]
Our coop members will each have an instance of peermusic installed that will be hard coded to our signalhub. Should we turn of the singalhub that starts at http://localhost:7000  before we set the peermusic instances up for our members ? 
If so where in the code can we turn off the signalhub that is running on http://localhost:7000 

Thanks for your help

**Comment by perguth** [comment]
Hm, why do you want to provide the peermusic website on every computer? Maybe you did not know that every instance (http://peermusic.github.io/ too) do aggressive caching and basically work without ever contacting the original server again.

**Comment by perguth** [comment]
How do you start the local peermusic server? (of course you should be able to start it without running a local signalhub)
