### ISSUE TITLE
How to add Album Art 

### ISSUE THREAD

**Issue by freedomtrain** [peermusic/desktop#58]
Is there a way to add album art and metadata to tracks and albums ?

**Comment by perguth** [comment]
Regarding manual adding of album art: nope, sorry, we didn't come to that.

But we wrote a module that can retrieve metadata automatically. If you set one up (~~https://github.com/peermusic/scrape-engine~~ https://github.com/peermusic/node-scraping-server) you can add that servers address under `Servers` -> `Scraping`.

**Comment by freedomtrain** [comment]
Thanks for your help.
I have installed the scrape engine.
Is there a command to start it ?
Do I need to add any other info to the server scraping section besides the address of the scraping server .....secret key etc ?

**Comment by perguth** [comment]
Sorry, I misdirected you there. It's this module you need to run: https://github.com/peermusic/node-scraping-server

You need to run it on some host that the peermusic client (the webbrowser can access - use the browsers developer console to debug). Create a user (see documentation in the repo) and then add  that servers address under `Servers -> Scraping`.
