### ISSUE TITLE
Loading duration of track for andriod

### ISSUE THREAD

**Issue by queicherius** [peermusic/desktop#6]
Chrome (47) on Andriod has **really** dumb behaviour when it comes to `<audio>`.

We are grabbing the duration of the audio file [here](https://github.com/peermusic/app/blob/6753c03e72a37121b9461b28bcf1f2f32da121bb/app/actions/songs.js#L35-L38) to save it as our max duration. This gets used e.g. to determine the max duration of the player (= without it we can't seek in the track).

Now the problem - on Andriod the `audio.duration` is `0` for the following events:
- `loadstart`
- `durationchange`
- `loadedmetadata`
- `loadeddata`
- `progress`
- `canplay`
- `canplaythrough`

I tried working around that by using `play()` and the `timeupdate` event, but Andriod supresses the function call with the message

> Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

Maybe we have to hack it in so it listens to the `timeupdate` event when the user presses play and updates the state if the duration is `0` from importing.

---

Reference: http://stackoverflow.com/questions/22719542/get-audio-duration-on-chrome-for-android

**Comment by queicherius** [comment]
The code is now hooking into the tap event of the user playing a song (`PLAYER_SET_PLAYING`) and Andriod accepts that as a gesture. Then we go through all songs that have a bugged duration, play them for one tick with 0 volume and read the actual duration off the `timeupdate` event. This is a bit hacky, but it works perfectly. :shipit:

**Comment by perguth** [comment]
xD omg
