### ISSUE TITLE
"playing" state visualization inconsistency

### ISSUE THREAD

**Issue by perguth** [peermusic/desktop#7]
To reproduce: Start playing a song, then pause it.

![playing or not](https://cdn.pbrd.co/images/IEJQPBV.png)

**Comment by queicherius** [comment]
The orange in the table only shows the currently selected song, not the playing one. Should we change that? @ryomiyaichi

**Comment by ryomiyaichi** [comment]
What about just toggling the state of the loudspeaker icon to hidden/show when we toggle the playing state and keeping the selected song in orange?

**Comment by perguth** [comment]
@ryomiyaichi :+1:. Keeping it orange is okay as it still **_is**_ the song that is selected for playback.

**Comment by queicherius** [comment]
I'd do that after #5 is merged. Then we have no merge conflicts. :smile:
